kind: pipeline
type: docker
name: test

steps:
  - name: composer
    image: composer:latest
    commands:
      - composer install

  - name: php74test
    image: registry.i15.nl/i15/fuzephp:7.4-alpine
    commands:
      - docker-php-ext-enable xdebug
      - vendor/bin/phpunit -c test/phpunit.xml

  - name: php80test
    image: registry.i15.nl/i15/fuzephp:8.0-alpine
    commands:
      - docker-php-ext-enable xdebug
      - vendor/bin/phpunit -c test/phpunit.xml

  - name: coverage
    image: registry.i15.nl/i15/fuzephp:8.0-alpine
    commands:
      - docker-php-ext-enable xdebug
      - vendor/bin/phpunit -c test/phpunit.xml --coverage-text

image_pull_secrets:
  - dockerconfig